import { useEffect, useState } from 'react';
import type { CatalogProduct } from '../../lib/catalog/server';
import { calculatePrice, discountPercent, money, type PricingSettings } from '../../lib/catalog/pricing';
import '../../styles/catalog.css';
type Props = { products: CatalogProduct[]; settings: PricingSettings; mode: 'packages' | 'questionnaires' | 'builder' };
export default function CatalogExplorer({ products, settings, mode }: Props) {
 const [search,setSearch]=useState(''); const [category,setCategory]=useState(''); const [audience,setAudience]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [ready,setReady]=useState(false);
 const questions=products.filter(p=>p.type==='questionnaire' && p.availability==='available' && p.priceCents!==null);
 useEffect(()=>{ try { const ids=JSON.parse(sessionStorage.getItem('mg-questionnaires')||'[]'); if(Array.isArray(ids))setSelected(ids.filter(x=>typeof x==='string' && questions.some(p=>p.id===x))); }catch{} const add=new URLSearchParams(window.location.search).get('voegtoe'); if(add&&questions.some(p=>p.id===add))setSelected(ids=>[...new Set([...ids,add])]); setReady(true); },[]);
 useEffect(()=>{ if(ready)try{sessionStorage.setItem('mg-questionnaires',JSON.stringify(selected));}catch{} },[selected,ready]);
 const toggle=(id:string)=>setSelected(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
 const kind=mode==='packages'?'profile':'questionnaire'; const visible=products.filter(p=>p.type===kind && p.availability!=='paused');
 const categories=[...new Set(visible.map(p=>p.category))];
 const shown=visible.filter(p=>(!category||p.category===category)&&(!audience||p.audience.toLowerCase().includes(audience))&&(!search||`${p.title} ${p.summary} ${p.category}`.toLowerCase().includes(search.toLowerCase())));
 const basket=questions.filter(p=>selected.includes(p.id)); const price=basket.length?calculatePrice(basket.map(p=>({id:p.id,priceCents:p.priceCents!})),'custom',settings):null;
 const next=basket.length<settings.mediumMin?settings.mediumMin:basket.length<settings.largeMin?settings.largeMin:0;
 return <div className={`catalog-explorer ${mode==='builder'?'has-basket':''}`}>
  <div className="catalog-main"><div className="catalog-controls"><label className="catalog-search"><span>Zoek jouw startpunt</span><input type="search" placeholder="Zoek op thema of vragenlijst…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label><span>Voor wie?</span><select value={audience} onChange={e=>setAudience(e.target.value)}><option value="">Iedereen</option><option value="kinderen">Kinderen</option><option value="jongeren">Jongeren</option><option value="volwassenen">Volwassenen</option></select></label></div>
   {mode!=='packages'&&<div className="catalog-chips" role="group" aria-label="Filter op thema"><button aria-pressed={!category} onClick={()=>setCategory('')}>Alle thema’s</button>{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>}
   <div className="catalog-result"><span aria-live="polite">{shown.length} {mode==='packages'?'profielen':'vragenlijsten'} gevonden</span>{(search||category||audience)&&<button onClick={()=>{setSearch('');setCategory('');setAudience('');}}>Filters wissen</button>}</div>
   <div className={`catalog-grid ${mode==='packages'?'package-grid':''}`}>{shown.map((p,i)=>{const available=p.availability==='available'&&p.priceCents!==null;const added=selected.includes(p.id);return <article key={p.id} className={`catalog-card ${added&&kind==='questionnaire'?'is-selected':''} ${p.slug==='stress-en-emotieprofiel'?'featured-package':''}`}>
    {mode==='packages'&&<div className="catalog-card-image"><img src={p.image} alt="" loading="lazy"/><span>{p.slug==='stress-en-emotieprofiel'?'Verdiepend profiel':`${p.components.length} onderdelen`}</span></div>}
    <div className="catalog-card-content"><div className="catalog-card-top"><span>{mode==='packages'?'Persoonlijk profiel':p.category}</span><b aria-hidden="true">{String(i+1).padStart(2,'0')}</b></div><h3><a href={`/${kind==='profile'?'profielen':'vragenlijsten'}/${p.slug}`}>{p.title}</a></h3><p>{p.summary}</p><div className="catalog-age">{p.ageLabel} <span>·</span> {p.audience}</div>
     {mode==='packages'&&<ul className="catalog-components">{p.components.map((c,j)=><li key={j}>{c.title}</li>)}</ul>}
     <div className="catalog-card-bottom">{available?<><div><small>{settings.priceLabel}</small><strong>{money(p.priceCents!)}</strong></div>{mode==='packages'?<a className="catalog-action" href={`/profielen/${p.slug}`}>Bekijk profiel <span aria-hidden="true">↗</span></a>:<button className="catalog-action" aria-pressed={added} onClick={()=>toggle(p.id)}>{added?'Toegevoegd ✓':'Toevoegen +'}<span className="sr-only"> {p.title}</span></button>}</>:<span className="catalog-upcoming">In ontwikkeling</span>}</div>
    </div></article>})}</div>
   {!shown.length&&<div className="catalog-no-results"><h3>Even opnieuw kijken?</h3><p>Probeer een ander thema of wis je filters.</p><button className="catalog-action" onClick={()=>{setSearch('');setCategory('');setAudience('');}}>Toon het aanbod</button></div>}
  </div>
  {mode==='builder'?<aside id="jouw-combinatie" className="catalog-basket" aria-label="Jouw samenstelling"><span className="catalog-kicker">Jouw combinatie</span><h2>Inzicht dat bij jou past.</h2><p>Combineer vragenlijsten voor één persoon. De korting volgt vanzelf.</p><div className="discount-steps">{[[1,0],[settings.mediumMin,settings.mediumPercent],[settings.largeMin,settings.largePercent]].map(([n,d],i)=><div key={i} className={basket.length>=n?'reached':''}><b>{i===2?`${n}+`:i===1?`${n}–${settings.largeMin-1}`:'1'}</b><span>{d}% korting</span></div>)}</div>
   {basket.length?<><ul className="basket-lines">{basket.map(p=><li key={p.id}><div><b>{p.title}</b><small>{p.ageLabel}</small></div><span>{money(p.priceCents!)}</span><button onClick={()=>toggle(p.id)} aria-label={`${p.title} verwijderen`}>×</button></li>)}</ul><div className="basket-totals"><div><span>Vragenlijsten ({basket.length})</span><span>{money(price!.subtotalCents)}</span></div>{price!.discountCents>0&&<div className="basket-saving"><span>Combinatiekorting {price!.discountPercent}%</span><span>−{money(price!.discountCents)}</span></div>}<div className="basket-total"><b>Totaal</b><strong>{money(price!.totalCents)}</strong></div></div>{next>0&&<p className="basket-next">Nog {next-basket.length} {next-basket.length===1?'vragenlijst':'vragenlijsten'} voor {discountPercent(next,settings)}% korting.</p>}<a className="catalog-checkout" href={`/bestellen?vragenlijsten=${basket.map(p=>p.id).join(',')}`}>Verder met mijn combinatie <span aria-hidden="true">→</span></a><button className="basket-clear" onClick={()=>setSelected([])}>Samenstelling wissen</button></>:<div className="basket-empty"><span aria-hidden="true">＋</span><p>Voeg je eerste vragenlijst toe.<br/>Je overzicht verschijnt hier.</p></div>}
   <small className="basket-note">Twijfel je over de juiste keuze of leeftijd? <a href="/contact">We denken graag met je mee.</a></small></aside>:null}
  {mode!=='packages'&&basket.length>0?<div className="catalog-floating" role="status"><div><b>{basket.length} geselecteerd</b><span>{money(price!.totalCents)}{price!.discountPercent>0?` · ${price!.discountPercent}% korting`:''}</span></div><a href={mode==='builder'?'#jouw-combinatie':'/samenstellen'}>Bekijk mijn combinatie →</a></div>:null}
 </div>;
}
